name: Fetch and Commit XML - main

on:
  schedule:
    - cron: '10 * * * *' # Every 10min

jobs:
  fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml

    - name: Run script to fetch and commit XML
      env:
        TZ: "Asia/Tokyo"
      run: python fetch.py

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        TZ: "Asia/Tokyo"
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /
        publish_branch: gh-pages
