name: Fetch and Commit

on:
  schedule:              # scheduleは branchのみで動作
    - cron: '5 * * * *' # 毎日深夜 2:30 に実行
env:
  GGLDRIVE_TOKEN: ${{secrets.GGLDRIVE_TOKEN}}
  TZ: "Asia/Tokyo"
jobs:
  fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script to fetch and commit
      run: python main.py

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
        enable_jekyll: true
        allow_empty_commit: true
        keep_files: false
