name: Fetch and Commit XML - main

on:
  schedule:
    - cron: '*/90 * * * *' # Every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script to fetch and commit XML
      run: python .github/scripts/fetch_and_commit_xml.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add fetched XML" || echo "No changes to commit"
        git push
